### PR TITLE
added missing fields to Cards.ts

### PR DESCRIPTION
**Pull request by sili3011**
reference:
https://scryfall.com/docs/api/cards

### CODE REVIEW

**Comment by ChiriVulpes** [comment]
Thanks for this! I will note that I’m in the middle of a fairly substantial usability update and don't bother with branches in this project, so it's going to take a little while for this to be merged and published on npm. Hope that's alright!

**Comment by multimeric** [comment]
Any update on this? I note that there are also some other changes needed, like allowing `card.layout` to include `modal_dfc`.

**Comment by sili3011** [comment]
> Any update on this? I note that there are also some other changes needed, like allowing `card.layout` to include `modal_dfc`.

I havent heard from them since, but I can look into it later, push changes and you can patch your package with this branches code

**Comment by multimeric** [comment]
That would be great, thanks!

**Comment by sili3011** [comment]
Done! Let me know if you notice something else missing.

**Comment by ChiriVulpes** [comment]
I'm gonna try to either finish everything and get a new sdk major version out today, or if I don't manage to finish it I'll just release a version under the beta tag

**Pull request merged**
